version: "3"

services:
  spark:
    build: .
    container_name: spark-jupyter
    ports:
      - "8888:8888"      # Jupyter Notebook
      - "4040:4040"      # Spark UI
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python
